[build]
  base = "docs"
  command = "yarn build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
